### PR TITLE
Updates to include P2PKH and P2WPKH classes in library exports

### PR DESCRIPTION
**Pull request by RohanKapurDEV**
Quick edit to library main file to include access to P2PKH class

### CODE REVIEW

**Comment by longhoangwkm** [comment]
@RohanKapurDEV why do you wanna to export this class. Could give me a context. And some export p2wpkh also if need

**Comment by RohanKapurDEV** [comment]
I wrote the following code while exploring how the library works:
I had to add that line to use P2PKH class.
`
bip44test() {
    final mnemonic = bip39.generateMnemonic();
    final seed = bip39.mnemonicToSeed(mnemonic);
    final root = bip32.BIP32.fromSeed(seed);

    final node1 = root.derivePath("m/44'/0'/0'/0/0"); // (m/ purpose' / coin_type' / account_index' / chain(external_or_change) / address_index(external_or_change))
    final node2 = root.derivePath("m/44'/0'/0'/0/1");
    final node3 = root.derivePath("m/44'/0'/0'/0/2");

    final address1 = P2PKH(data: new P2PKHData(pubkey: node1.publicKey)).data.address; 
    final address2 = P2PKH(data: new P2PKHData(pubkey: node2.publicKey)).data.address; 
    final address3 = P2PKH(data: new P2PKHData(pubkey: node3.publicKey)).data.address; 
    
    final changeNode1 = root.derivePath("m/44'/0'/0'/1/0"); 
    final changeNode2 = root.derivePath("m/44'/0'/0'/1/1"); 
    final changeNode3 = root.derivePath("m/44'/0'/0'/1/2");

    final changeAddress1 = P2PKH(data: new P2PKHData(pubkey: changeNode1.publicKey)).data.address; 
    final changeAddress2 = P2PKH(data: new P2PKHData(pubkey: changeNode2.publicKey)).data.address; 
    final changeAddress3 = P2PKH(data: new P2PKHData(pubkey: changeNode3.publicKey)).data.address; 

    print('''
    BIP39 Mnemonic: $mnemonic
    BIP32 Master Node: $root
    
    BIP44 Receiving Address 1: $address1
    BIP44 Receiving Address 2: $address2
    BIP44 Receiving Address 3: $address3

    BIP44 Change Address 1: $changeAddress1
    BIP44 Change Address 1: $changeAddress2
    BIP44 Change Address 1: $changeAddress3
    ''');
  }
`

**Comment by RohanKapurDEV** [comment]
It is just random test code, not to be used in any real app. Only for exploring library

**Comment by longhoangwkm** [comment]
i see, please help me export `p2wpkh.dart` also

btw, Using "```dart" "```" to embed code

**Comment by RohanKapurDEV** [comment]
Ok, p2wpkh has also been added!

**Comment by longhoangwkm** [comment]
just run test. 1 failed. 
Help me move `final EMPTY_SCRIPT = Uint8List.fromList([]);`at lib/src/payments/p2wpkh.dart go go inside `P2WPKH` class. Due to `EMPTY_SCRIPT` already export at `transaction.dart`

**Comment by RohanKapurDEV** [comment]
P2WPKH class has been updated to include EMPTY_SCRIPT

**Comment by longhoangwkm** [comment]
LGTM

**Pull request merged**
